# Generated by Django 4.0.5 on 2022-06-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tontinerecipient",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="meeting",
            name="tontine_recipients",
            field=models.ManyToManyField(
                related_name="recipient_dates",
                through="ade4.TontineRecipient",
                to="ade4.member",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="registration_date",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ade4.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="tontinerecipient",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_dates",
                to="ade4.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="tontinerecipient",
            name="tontine_round",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ade4.tontineround",
            ),
        ),
    ]
