# Generated by Django 4.0.5 on 2022-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0002_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
