# Generated by Django 4.0.5 on 2022-06-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0002_alter_tontinerecipient_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="end_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="end_board",
                to="ade4.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="start_date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_board",
                to="ade4.meeting",
            ),
        ),
    ]
