# Generated by Django 4.0.5 on 2022-06-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0005_alter_meeting_date_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="constants",
            options={"verbose_name": "Constants", "verbose_name_plural": "Constants"},
        ),
        migrations.CreateModel(
            name="ReceptionRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "end_date",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="end_reception_round",
                        to="ade4.meeting",
                        to_field="date",
                    ),
                ),
                (
                    "start_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_reception_round",
                        to="ade4.meeting",
                        to_field="date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reception Round",
                "verbose_name_plural": "Reception Rounds",
                "ordering": ["-start_date__date"],
            },
        ),
    ]
