# Generated by Django 4.0.5 on 2022-06-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0006_alter_address_options_alter_constants_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_list",
                        to="ade4.meeting",
                        to_field="date",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_list",
                        to="ade4.member",
                    ),
                ),
                (
                    "reception_round",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ade4.receptionround",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="hosts",
            field=models.ManyToManyField(
                related_name="hosted_meetings", through="ade4.Hosts", to="ade4.member"
            ),
        ),
    ]
