# Generated by Django 4.0.5 on 2022-06-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0009_alter_accounttype_used_for"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccountType",
            new_name="Account",
        ),
    ]
