# Generated by Django 4.0.5 on 2022-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0012_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=100, unique=True, verbose_name="Poste"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
