# Generated by Django 4.0.5 on 2022-06-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ade4", "0014_boardmember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={"ordering": ["-created_at"]},
        ),
    ]
