# Generated by Django 4.0.5 on 2022-06-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0016_accounttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='MemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ade4.accounttype')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ade4.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ade4.member')),
            ],
            options={
                'verbose_name': 'Member Transaction',
                'verbose_name_plural': 'Member Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
