# Generated by Django 4.0.5 on 2022-06-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0019_alter_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='email',
            new_name='user',
        ),
    ]
