# Generated by Django 4.0.5 on 2022-06-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0021_user_alter_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name': 'Type Document',
                'verbose_name_plural': 'Type Documents',
            },
        ),
    ]
