# Generated by Django 4.0.5 on 2022-06-12 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0022_doctype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocType',
            new_name='DocumentType',
        ),
        migrations.CreateModel(
            name='DocumentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('chapter_number', models.PositiveSmallIntegerField(blank=True, verbose_name='N°')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ade4.documenttype')),
            ],
            options={
                'ordering': ['doc_type', 'title'],
            },
        ),
    ]
