# Generated by Django 4.0.5 on 2022-06-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0023_rename_doctype_documenttype_documentchapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchapter',
            options={'ordering': ['doc_type', 'title'], 'verbose_name': 'Document Chapter', 'verbose_name_plural': 'Document Chapters'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.CreateModel(
            name='DocumentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('article_number', models.PositiveSmallIntegerField(blank=True, verbose_name='N°')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='ade4.documentchapter')),
            ],
            options={
                'verbose_name': 'Document Article',
                'verbose_name_plural': 'Document Articles',
                'ordering': ['chapter__doc_type', 'chapter', 'article_number'],
            },
        ),
    ]
