# Generated by Django 4.0.5 on 2022-06-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ade4', '0024_alter_documentchapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ordre du jour'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='finance_ok',
            field=models.BooleanField(default=False, verbose_name='Finances OK?'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Rapport'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sanction_ok',
            field=models.BooleanField(default=False, verbose_name='Sanctions OK?'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('REGULAR', 'Séance Ordinaire'), ('EXTRAORDINARY', 'Séance Extraordinaire')], default='REGULAR', max_length=15, verbose_name='Type Séance'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Séance Validée'),
        ),
    ]
